version: "3.9"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/migration.sql:/docker-entrypoint-initdb.d/migration.sql

  backend:
    build:
      context: ./untitledGameBackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./untitled_game_frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend